/* Entire pipeline on fabricated data. These records do not describe people.
   Requires SAS/STAT with PROC PSMATCH; no confidential inputs are accessed. */
%let code_root=%qsysfunc(sysget(MA_DID_CODE));
%include "&code_root./00_config.sas";
%include "&code_root./01_utilities.sas";
data _null_;
  length path $2048;
  path=dcreate('synthetic_raw',sysget('MA_DID_TEST_OUT'));
  if missing(path) then abort cancel;
  call symputx('raw_root',path,'g');
run;
libname fixture "&raw_root.";
data fixture.koweps_hp01_12_long;
  do h_pid=1 to 400;
    h_id=ceil(h_pid/2); /* Shared lineage, distinct complete household keys. */
    do survey_year=2010 to 2016;
      year=survey_year-1;
      h_merkey=h_pid*100+survey_year-2000;
      event_year=2013+mod(h_pid,2);
      aid_type=0;
      if h_pid<=40 then aid_type=1;
      else if h_pid<=80 then aid_type=2;
      h01_5aq3=0;
      if aid_type>0 and survey_year>=event_year then h01_5aq3=aid_type;
      h01_11aq5=h01_5aq3;
      h_reg7=1+mod(h_pid,7); h_din=2000+100*mod(h_pid,40);
      h01_1=1+mod(h_pid,4); h_hc=1;
      h_g3=1+mod(floor(h_pid/2),2); h_g4=1940+mod(h_pid,50);
      h_g10=1+mod(h_pid,6); h_eco4=1+mod(h_pid,9);
      h_med2=1+mod(h_pid,5); h_med10=mod(h_pid,4);
      h_g9_1=mod(h_pid,4); h_med7=1+mod(h_pid,5);
      h_med3=mod(h_pid,9)+2*(survey_year-2010)+3*(h01_5aq3>0)+mod(h_pid*survey_year,3);
      h_med4=mod(h_pid+survey_year,3); h_med5=2*h_med4;
      output;
    end;
  end;
  keep h_pid h_id year h_merkey h01_5aq3 h01_11aq5 h_reg7 h_din h01_1 h_hc
    h_g3 h_g4 h_g10 h_eco4 h_med2 h_med10 h_g9_1 h_med7 h_med3 h_med4 h_med5;
run;
%macro fake_household(wave,sy,member);
  %local p;
  %let p=h%sysfunc(putn(&wave.,z2.));
  data fixture.&member.;
    set fixture.koweps_hp01_12_long;
    if year=&sy.-1;
    &p._merkey=h_merkey; &p._id=h_id; &p.01_5aq3=h01_5aq3;
    &p.07_3aq8=10+mod(h_pid,8)+0.3*(&sy.-2010)+0.5*(h01_5aq3>0);
    &p.05_3aq2=mod(h_pid,12);
    keep &p._merkey &p._id &p.01_5aq3 &p.07_3aq8 &p.05_3aq2;
  run;
%mend;
%fake_household(5,2010,koweps_h05_2010_beta10);
%fake_household(6,2011,koweps_h06_2011_beta8);
%fake_household(7,2012,koweps_h07_2012_beta8);
%fake_household(8,2013,koweps_h08_2013_beta6);
%fake_household(9,2014,koweps_h09_2014_beta4);
%fake_household(10,2015,koweps_h10_2015_beta3);
%fake_household(11,2016,koweps_h11_2016_beta2);
libname fixture clear;
%initialize;
%include "&code_root./02_build_panel.sas";
%include "&code_root./03_define_cohorts.sas";
%include "&code_root./04_match.sas";
%include "&code_root./05_build_windows.sas";
%include "&code_root./06_models.sas";
%include "&code_root./07_reports.sas";
%guard(Synthetic full pipeline);
%macro check_pipeline;
  %local n types windows eligible;
  proc sql noprint;
    select count(*) into :n trimmed from out.panel;
    select count(*) into :eligible trimmed from out.eligible_cases;
    select count(distinct aid_type),count(distinct window) into :types trimmed,:windows trimmed
      from out.analysis_panel;
  quit;
  %if &n. ne 2800 %then %fail(Synthetic household join did not preserve all 2800 rows);
  %if &eligible. ne 80 %then %fail(Synthetic cohort should have 80 eligible switchers);
  %if &types. ne 2 or &windows. ne 3 %then %fail(Synthetic matching did not support both types and all windows);
%mend;
%check_pipeline;
%put NOTE: PIPELINE_TESTS_PASSED;
